FROM elixir:latest

RUN apt-get update && apt-get upgrade -y

# update and install software
RUN apt-get install -y curl wget git make sudo inotify-tools

# install the Phoenix Mix archive
RUN mix archive.install --force https://github.com/phoenixframework/archives/raw/master/phx_new.ez

RUN mix local.hex --force \
    && mix local.rebar --force

# node.js
RUN curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - && sudo apt-get install -y nodejs \
    && rm -rf /var/cache/apt

EXPOSE 4000

WORKDIR /app
